[package]
name = "random_word"
description = "Reliable and efficient functions for generating random english words"
version = "0.3.0"
edition = "2021"
authors = ["Mitchell Rhys Hall"]
repository = "https://github.com/MitchellRhysHall/random_word"
license = "MIT"
categories = []
keywords = [
    "random",
    "words",
    "generate",
    "english",
]
readme = "README.md"

[dependencies]
rand = "0.8.5"
once_cell = "1.17.1"