[package]
name = "random_word"
description = "Simple functions for generating random english words"
version = "0.1.0"
edition = "2021"
authors = ["Mitchell Rhys Hall"]
license = "MIT"
categories = [
    "Random", 
    "Words"
]
keywords = [
    "random",
    "words",
    "generate",
]
readme = "README.md"
maintenance = { status = "experimental" }

[dependencies]
reqwest = "0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"