[package]
name = "random_word"
description = "Simple functions for generating random english words"
version = "0.1.1"
edition = "2021"
authors = ["Mitchell Rhys Hall"]
repository = "https://github.com/MitchellRhysHall/random_word"
license = "MIT"
categories = []
keywords = [
    "random",
    "words",
    "generate",
]
readme = "README.md"
maintenance = { status = "experimental" }

[dependencies]
reqwest = "0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"