[package]
name = "random_word"
description = "Reliable and efficient functions for generating random english words"
version = "0.2.3"
edition = "2021"
authors = ["Mitchell Rhys Hall"]
repository = "https://github.com/MitchellRhysHall/random_word"
license = "MIT"
categories = []
keywords = [
    "random",
    "words",
    "generate",
    "english",
]
readme = "README.md"
maintenance = { status = "experimental" }

[dependencies]
rand = "0"